services:
  php-apache:
    build: ./docker/web
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
      - 443:443
    networks:
      - my_network
volumes:
  mysql_db_data: {}
networks:
  my_network:
    driver: bridge
